### ISSUE TITLE
In phel v0.15, I want to use latest version of chemaclass/phel-cli-gui

### ISSUE THREAD

**Issue by smeghead** [Chemaclass/phel-cli-gui#1]
Here are the repositories I was trying out
https://github.com/smeghead/phel-lifegame

When I run `composer require chemaclass/phel-cli-gui` in a phel-lang v0.15 environment, v0.2.0 is installed instead of the latest version (v0.3.0).

Is this because chemaclass/phel-cli-gui:v0.3.0 specifies ^7.2 for the symfony/console version requirement?

Is there a good way to use chemaclass/phel-cli-gui:v0.3.0 in a phel v0.15 environment?

**Comment by Chemaclass** [comment]
Can you try again, @smeghead? I [changed the code](https://github.com/Chemaclass/phel-cli-gui/commit/27ba34ffd73455fea7fb46ef78b28dde53976c02) to depend on `"symfony/console": "^7.1"` and created a new tag `0.3.1`, this will help answering your question. Let me know if this fixes it or we need to get deeper on it.

> Extra hint: you can use this project as example of usage of that package https://github.com/Chemaclass/phel-snake

**Comment by smeghead** [comment]
@Chemaclass 
Thank you for the super fast response.
Installing chemaclass/phel-cli-gui (0.3.1)
I was able to install the latest version.
